from .embeddings import get_embedding_function
from .store import ingest_knowledge_base, is_knowledge_base_ingested, get_collection_stats
from .retrieval import retrieve_relevant_law, retrieve_for_policy_category
